version: "3.8"

services:
  social_network_db:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  dev:
    depends_on:
      - social_network_db
    container_name: social_network_api_dev
    image: social_network_api_dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run dev
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: social_network_api_prod
    image: social_network_api_prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  db:
