version: '3.8'

services:
  basic_api_node_template_db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
    networks:
      - basic_api_node_template_networks
  dev:
    depends_on:
      - basic_api_node_template_db
    container_name: basic_api_node_template_api_dev
    image: basic_api_node_template_api_dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run dev
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - basic_api_node_template_networks
  prod:
    container_name: basic_api_node_template_api_prod
    image: basic_api_node_template_api_prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  basic_api_node_template_networks:
    driver: bridge

volumes:
  db:
