@apiurl = http://localhost:3000/api

### GET users
GET {{apiurl}}/users HTTP/1.1

### GET user by id
GET {{apiurl}}/users/5 HTTP/1.1

### POST users
POST {{apiurl}}/signup HTTP/1.1
content-type: application/json

{
    "firstName":"Yvan",
    "lastName":"Brito",
    "age":27,
    "birthday":"1996-01-26T12:00:00Z",
    "email": "yvan@test.com",
    "password": "123456"
}

### POST login user
POST {{apiurl}}/login HTTP/1.1
content-type: application/json

{
    "email": "yvan@test.com",
    "password": "123456"
}